# Generated by Django 5.2.4 on 2026-09-25 10:35

import apps.core.uploads
import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_type', models.CharField(choices=[('barber', 'Barber'), ('salon', 'Salon')], db_index=True, max_length=20)),
                ('display_name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=apps.core.uploads.professional_profile_image_upload_to, validators=[apps.core.validators.validate_image_file])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.core.uploads.professional_cover_upload_to, validators=[apps.core.validators.validate_image_file])),
                ('is_verified', models.BooleanField(default=False, help_text='Set by staff only — powers the verified badge.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive profiles are hidden from public search.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'professional',
                'verbose_name_plural': 'professionals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.core.uploads.gallery_upload_to, validators=[apps.core.validators.validate_image_file])),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'gallery image',
                'verbose_name_plural': 'gallery images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.core.uploads.portfolio_upload_to, validators=[apps.core.validators.validate_image_file])),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'portfolio image',
                'verbose_name_plural': 'portfolio images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'favorite',
                'verbose_name_plural': 'favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'day off',
                'verbose_name_plural': 'days off',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_times', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'break time',
                'verbose_name_plural': 'break times',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BarberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('show_price', models.BooleanField(default=False)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'barber profile',
                'verbose_name_plural': 'barber profiles',
            },
        ),
        migrations.CreateModel(
            name='SalonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('number_of_workers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('show_price', models.BooleanField(default=False)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon_profile', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'salon profile',
                'verbose_name_plural': 'salon profiles',
            },
        ),
        migrations.CreateModel(
            name='SalonMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_memberships', to='professionals.barberprofile')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='professionals.salonprofile')),
            ],
            options={
                'verbose_name': 'salon team member',
                'verbose_name_plural': 'salon team members',
                'ordering': ['position', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_open', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'working hour',
                'verbose_name_plural': 'working hours',
                'ordering': ['weekday'],
            },
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['professional_type'], name='professiona_profess_c797b1_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['city'], name='professiona_city_5778a1_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['is_active', 'is_verified'], name='professiona_is_acti_b13b94_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='professiona_latitud_a5301c_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'professional'), name='unique_user_favorite'),
        ),
        migrations.AddConstraint(
            model_name='dayoff',
            constraint=models.UniqueConstraint(fields=('professional', 'date'), name='unique_professional_dayoff'),
        ),
        migrations.AddConstraint(
            model_name='salonmember',
            constraint=models.UniqueConstraint(fields=('salon', 'barber'), name='unique_salon_barber'),
        ),
        migrations.AddConstraint(
            model_name='workinghour',
            constraint=models.UniqueConstraint(fields=('professional', 'weekday'), name='unique_professional_weekday'),
        ),
    ]
